version: "3.1"

services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "15432:5432"
        volumes:
            - ./src/testPerformance/testDBpostgres.sql:/docker-entrypoint-initdb.d/testDB.sql
        environment:
            POSTGRES_PASSWORD: "404363289"
            POSTGRES_DB: "performance"

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "13306:3306"
        volumes:
            - ./src/testPerformance/testDBmysql.sql:/docker-entrypoint-initdb.d/testDB.sql
        environment:
            MYSQL_ROOT_PASSWORD: "404363289"

    explorer:
        image: performancetest:latest
        restart: always
        network_mode: host
        

    adminer:
        image: adminer
        restart: always
        ports:
            - "18080:8080"
