version: "3.1"

services:
    performancetestmysql:
        restart: always
        image: performancetest:latest
        build:
            context: ./
        environment:
            - mysqlPort=13306
            - mysqlHost=server.local
            - mysqlUser=root
            - mysqlPassword=404363289
            - mysqlDatabase=performance
        volumes:
            - ./benchMysql.log:/usr/src/app/dist/bench.log
        command: ["node", "/usr/src/app/dist/src/testPerformance/mysql"]
