version: "3.1"

services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "404363289"

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: "404363289"

    adminer:
        image: adminer
        restart: always
