version: "3.1"

services:
    performancetestexplorer1:
        restart: always
        network_mode: host
        image: performancetest:latest
        build:
            context: ./
        volumes:
            - ./benchExplorer.log:/usr/src/app/dist/bench.log
        command: ["node", "/usr/src/app/dist/src/testPerformance/explorer"]

    performancetestexplorer2:
        restart: always
        network_mode: host
        image: performancetest:latest
        build:
            context: ./
        volumes:
            - ./benchExplorer.log:/usr/src/app/dist/bench.log
        command: ["node", "/usr/src/app/dist/src/testPerformance/explorer"]

    performancetestexplorer3:
        restart: always
        network_mode: host
        image: performancetest:latest
        build:
            context: ./
        volumes:
            - ./benchExplorer.log:/usr/src/app/dist/bench.log
        command: ["node", "/usr/src/app/dist/src/testPerformance/explorer"]

    performancetestexplorer5:
        restart: always
        network_mode: host
        image: performancetest:latest
        build:
            context: ./
        volumes:
            - ./benchExplorer.log:/usr/src/app/dist/bench.log
        command: ["node", "/usr/src/app/dist/src/testPerformance/explorer"]

    performancetestexplorer4:
        restart: always
        network_mode: host
        image: performancetest:latest
        build:
            context: ./
        volumes:
            - ./benchExplorer.log:/usr/src/app/dist/bench.log
        command: ["node", "/usr/src/app/dist/src/testPerformance/explorer"]
