version: "3.1"

services:
    performancetestPostgres:
        restart: always
        image: performancetest:latest
        build:
            context: ./
        environment:
            - postgresPort=15432
            - postgresHost=server.local
            - postgresUser=postgres
            - postgresPassword=404363289
            - postgresDatabase=performance
        volumes:
            - ./benchPostgres.log:/usr/src/app/dist/bench.log
        command: ["node", "/usr/src/app/dist/src/testPerformance/postgres"]
